import '../../contracts/contracts.dart';

// Fixed RC2.1 snapshots; no economy or persistence.
GameState newDemoFixture() => GameState(
  contractVersion: "logic_contract_v0.1",
  contentVersion: "content_v0.2",
  stateRevision: 1,
  profile: Profile(
    id: "profile.demo.01",
    mode: ProfileMode.demo,
    displayName: null,
    petName: "Финни",
    generation: 1,
    createdAt: DateTime.parse("2026-09-24T09:00:00Z"),
    updatedAt: DateTime.parse("2026-09-24T09:00:00Z"),
  ),
  currentPeriod: PeriodState(
    id: "profile.demo.01.g1.p1",
    number: 1,
    status: PeriodStatus.open,
    incomeCredited: 100,
    incomeCreditedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    availableItemIds: [
      "item.food",
      "item.hygiene",
      "item.ball",
      "item.music_player",
    ],
    requiredPurchases: [
      RequiredPurchase(itemId: "item.food", quantity: 1, fulfilled: false),
      RequiredPurchase(itemId: "item.hygiene", quantity: 1, fulfilled: false),
    ],
    purchaseSlotsTotal: 3,
    purchaseSlotsUsed: 0,
    purchasedItemIds: [],
    budgetPlan: null,
    actual: BudgetActual(
      periodIncome: 100,
      taskRewards: 0,
      needsSpent: 0,
      wantsSpent: 0,
      savingsDeposited: 0,
      ordinarySavingsWithdrawn: 0,
      goalRedemptionSpent: 0,
      qualifyingSavings: 0,
      savingsMoodBonusGranted: false,
      requiredNeedsMet: false,
      planKept: false,
      savingsHabitKept: false,
    ),
    startedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    closedAt: null,
  ),
  availableBalance: 100,
  savingsBalance: 0,
  activeGoal: null,
  pet: PetState(
    name: "Финни",
    formId: "pet.form.01",
    paletteId: "pet.palette.01",
    satiety: 60,
    mood: 60,
    moodCode: MoodCode.calm,
    stage: PetStage.baby,
    lastReasonCode: "profile_created",
    explanationForChild: "Финни готов учиться вместе с тобой.",
  ),
  taskHub: TaskHub(
    recommendedTask: TaskSummary(
      id: "task.budget.01",
      title: "Распредели доход",
      theme: TaskTheme.budget,
      interactionType: TaskInteractionType.budgetAllocation,
      rewardAmount: 5,
      availability: TaskAvailabilityCode.available,
      unavailableReason: null,
      completed: false,
      rewardState: RewardState.available,
      attemptsThisPeriod: 0,
      remainingAttempts: 3,
    ),
    tasks: [
      TaskSummary(
        id: "task.budget.01",
        title: "Распредели доход",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.budgetAllocation,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.budget.02",
        title: "Сравни план и факт",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.planFactChoice,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.savings.01",
        title: "Составь путь к цели",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsSchedule,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.savings.02",
        title: "Посчитай накопления",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsComparison,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.01",
        title: "Собери корзину",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.purchaseBasket,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.02",
        title: "Нужное или желаемое",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.expenseClassification,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
    ],
  ),
  learningProgress: LearningProgress(
    completedPeriods: 0,
    qualityPoints: 0,
    taskProgress: [
      TaskProgress(
        taskId: "task.budget.01",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.budget.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.savings.01",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.savings.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.01",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
    ],
    stageHistory: [
      StageHistoryEntry(
        stage: PetStage.baby,
        reachedAfterPeriod: 0,
        qualityPoints: 0,
        reachedAt: DateTime.parse("2026-09-24T09:00:00Z"),
      ),
    ],
  ),
  settings: ProfileSettings(
    soundEnabled: true,
    reducedMotion: false,
    largeTextPreferred: false,
  ),
);
GameState openPeriodFixture() => GameState(
  contractVersion: "logic_contract_v0.1",
  contentVersion: "content_v0.2",
  stateRevision: 9,
  profile: Profile(
    id: "profile.demo.01",
    mode: ProfileMode.demo,
    displayName: null,
    petName: "Финни",
    generation: 1,
    createdAt: DateTime.parse("2026-09-24T09:00:00Z"),
    updatedAt: DateTime.parse("2026-09-24T09:18:00Z"),
  ),
  currentPeriod: PeriodState(
    id: "profile.demo.01.g1.p1",
    number: 1,
    status: PeriodStatus.open,
    incomeCredited: 100,
    incomeCreditedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    availableItemIds: [
      "item.food",
      "item.hygiene",
      "item.ball",
      "item.music_player",
    ],
    requiredPurchases: [
      RequiredPurchase(itemId: "item.food", quantity: 1, fulfilled: true),
      RequiredPurchase(itemId: "item.hygiene", quantity: 1, fulfilled: true),
    ],
    purchaseSlotsTotal: 3,
    purchaseSlotsUsed: 2,
    purchasedItemIds: ["item.food", "item.hygiene"],
    budgetPlan: BudgetPlan(
      periodId: "profile.demo.01.g1.p1",
      needsLimit: 50,
      wantsLimit: 20,
      savingsTarget: 30,
      unallocatedAmount: 0,
      requiredNeedsCostAtConfirmation: 50,
      confirmedAt: DateTime.parse("2026-09-24T09:02:00Z"),
    ),
    actual: BudgetActual(
      periodIncome: 100,
      taskRewards: 10,
      needsSpent: 50,
      wantsSpent: 0,
      savingsDeposited: 30,
      ordinarySavingsWithdrawn: 0,
      goalRedemptionSpent: 0,
      qualifyingSavings: 30,
      savingsMoodBonusGranted: true,
      requiredNeedsMet: true,
      planKept: true,
      savingsHabitKept: true,
    ),
    startedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    closedAt: null,
  ),
  availableBalance: 30,
  savingsBalance: 30,
  activeGoal: GoalProgress(
    goalId: "goal.playground",
    title: "Игровая площадка для Финни",
    targetAmount: 120,
    savedAmount: 30,
    remainingAmount: 90,
    status: GoalStatus.selected,
    selectedAt: DateTime.parse("2026-09-24T09:03:00Z"),
    completedAt: null,
  ),
  pet: PetState(
    name: "Финни",
    formId: "pet.form.01",
    paletteId: "pet.palette.01",
    satiety: 75,
    mood: 80,
    moodCode: MoodCode.happy,
    stage: PetStage.baby,
    lastReasonCode: "savings_deposit",
    explanationForChild: "Часть монет стала ближе к цели.",
  ),
  taskHub: TaskHub(
    recommendedTask: TaskSummary(
      id: "task.budget.02",
      title: "Сравни план и факт",
      theme: TaskTheme.budget,
      interactionType: TaskInteractionType.planFactChoice,
      rewardAmount: 5,
      availability: TaskAvailabilityCode.available,
      unavailableReason: null,
      completed: false,
      rewardState: RewardState.available,
      attemptsThisPeriod: 0,
      remainingAttempts: 3,
    ),
    tasks: [
      TaskSummary(
        id: "task.budget.01",
        title: "Распредели доход",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.budgetAllocation,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.completedReview,
        unavailableReason: null,
        completed: true,
        rewardState: RewardState.granted,
        attemptsThisPeriod: 1,
        remainingAttempts: 2,
      ),
      TaskSummary(
        id: "task.budget.02",
        title: "Сравни план и факт",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.planFactChoice,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.savings.01",
        title: "Составь путь к цели",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsSchedule,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.completedReview,
        unavailableReason: null,
        completed: true,
        rewardState: RewardState.granted,
        attemptsThisPeriod: 1,
        remainingAttempts: 2,
      ),
      TaskSummary(
        id: "task.savings.02",
        title: "Посчитай накопления",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsComparison,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.01",
        title: "Собери корзину",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.purchaseBasket,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.02",
        title: "Нужное или желаемое",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.expenseClassification,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
    ],
  ),
  learningProgress: LearningProgress(
    completedPeriods: 0,
    qualityPoints: 0,
    taskProgress: [
      TaskProgress(
        taskId: "task.budget.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 1,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:05:00Z"),
      ),
      TaskProgress(
        taskId: "task.budget.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.savings.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 1,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:07:00Z"),
      ),
      TaskProgress(
        taskId: "task.savings.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.01",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
    ],
    stageHistory: [
      StageHistoryEntry(
        stage: PetStage.baby,
        reachedAfterPeriod: 0,
        qualityPoints: 0,
        reachedAt: DateTime.parse("2026-09-24T09:00:00Z"),
      ),
    ],
  ),
  settings: ProfileSettings(
    soundEnabled: true,
    reducedMotion: false,
    largeTextPreferred: false,
  ),
);
GameState withdrawnFixture() => GameState(
  contractVersion: "logic_contract_v0.1",
  contentVersion: "content_v0.2",
  stateRevision: 10,
  profile: Profile(
    id: "profile.demo.01",
    mode: ProfileMode.demo,
    displayName: null,
    petName: "Финни",
    generation: 1,
    createdAt: DateTime.parse("2026-09-24T09:00:00Z"),
    updatedAt: DateTime.parse("2026-09-24T09:19:00Z"),
  ),
  currentPeriod: PeriodState(
    id: "profile.demo.01.g1.p1",
    number: 1,
    status: PeriodStatus.open,
    incomeCredited: 100,
    incomeCreditedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    availableItemIds: [
      "item.food",
      "item.hygiene",
      "item.ball",
      "item.music_player",
    ],
    requiredPurchases: [
      RequiredPurchase(itemId: "item.food", quantity: 1, fulfilled: true),
      RequiredPurchase(itemId: "item.hygiene", quantity: 1, fulfilled: true),
    ],
    purchaseSlotsTotal: 3,
    purchaseSlotsUsed: 2,
    purchasedItemIds: ["item.food", "item.hygiene"],
    budgetPlan: BudgetPlan(
      periodId: "profile.demo.01.g1.p1",
      needsLimit: 50,
      wantsLimit: 20,
      savingsTarget: 30,
      unallocatedAmount: 0,
      requiredNeedsCostAtConfirmation: 50,
      confirmedAt: DateTime.parse("2026-09-24T09:02:00Z"),
    ),
    actual: BudgetActual(
      periodIncome: 100,
      taskRewards: 10,
      needsSpent: 50,
      wantsSpent: 0,
      savingsDeposited: 30,
      ordinarySavingsWithdrawn: 10,
      goalRedemptionSpent: 0,
      qualifyingSavings: 20,
      savingsMoodBonusGranted: true,
      requiredNeedsMet: true,
      planKept: false,
      savingsHabitKept: true,
    ),
    startedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    closedAt: null,
  ),
  availableBalance: 40,
  savingsBalance: 20,
  activeGoal: GoalProgress(
    goalId: "goal.playground",
    title: "Игровая площадка для Финни",
    targetAmount: 120,
    savedAmount: 20,
    remainingAmount: 100,
    status: GoalStatus.selected,
    selectedAt: DateTime.parse("2026-09-24T09:03:00Z"),
    completedAt: null,
  ),
  pet: PetState(
    name: "Финни",
    formId: "pet.form.01",
    paletteId: "pet.palette.01",
    satiety: 75,
    mood: 80,
    moodCode: MoodCode.happy,
    stage: PetStage.baby,
    lastReasonCode: "savings_withdrawal",
    explanationForChild:
        "Монеты снова доступны; прогресс этого периода пересчитан.",
  ),
  taskHub: TaskHub(
    recommendedTask: TaskSummary(
      id: "task.budget.02",
      title: "Сравни план и факт",
      theme: TaskTheme.budget,
      interactionType: TaskInteractionType.planFactChoice,
      rewardAmount: 5,
      availability: TaskAvailabilityCode.available,
      unavailableReason: null,
      completed: false,
      rewardState: RewardState.available,
      attemptsThisPeriod: 0,
      remainingAttempts: 3,
    ),
    tasks: [
      TaskSummary(
        id: "task.budget.01",
        title: "Распредели доход",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.budgetAllocation,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.completedReview,
        unavailableReason: null,
        completed: true,
        rewardState: RewardState.granted,
        attemptsThisPeriod: 1,
        remainingAttempts: 2,
      ),
      TaskSummary(
        id: "task.budget.02",
        title: "Сравни план и факт",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.planFactChoice,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.savings.01",
        title: "Составь путь к цели",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsSchedule,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.completedReview,
        unavailableReason: null,
        completed: true,
        rewardState: RewardState.granted,
        attemptsThisPeriod: 1,
        remainingAttempts: 2,
      ),
      TaskSummary(
        id: "task.savings.02",
        title: "Посчитай накопления",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsComparison,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.01",
        title: "Собери корзину",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.purchaseBasket,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.02",
        title: "Нужное или желаемое",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.expenseClassification,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.available,
        unavailableReason: null,
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
    ],
  ),
  learningProgress: LearningProgress(
    completedPeriods: 0,
    qualityPoints: 0,
    taskProgress: [
      TaskProgress(
        taskId: "task.budget.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 1,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:05:00Z"),
      ),
      TaskProgress(
        taskId: "task.budget.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.savings.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 1,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:07:00Z"),
      ),
      TaskProgress(
        taskId: "task.savings.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.01",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
    ],
    stageHistory: [
      StageHistoryEntry(
        stage: PetStage.baby,
        reachedAfterPeriod: 0,
        qualityPoints: 0,
        reachedAt: DateTime.parse("2026-09-24T09:00:00Z"),
      ),
    ],
  ),
  settings: ProfileSettings(
    soundEnabled: true,
    reducedMotion: false,
    largeTextPreferred: false,
  ),
);
GameState closedFixture() => GameState(
  contractVersion: "logic_contract_v0.1",
  contentVersion: "content_v0.2",
  stateRevision: 10,
  profile: Profile(
    id: "profile.demo.01",
    mode: ProfileMode.demo,
    displayName: null,
    petName: "Финни",
    generation: 1,
    createdAt: DateTime.parse("2026-09-24T09:00:00Z"),
    updatedAt: DateTime.parse("2026-09-24T09:20:00Z"),
  ),
  currentPeriod: PeriodState(
    id: "profile.demo.01.g1.p1",
    number: 1,
    status: PeriodStatus.closed,
    incomeCredited: 100,
    incomeCreditedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    availableItemIds: [
      "item.food",
      "item.hygiene",
      "item.ball",
      "item.music_player",
    ],
    requiredPurchases: [
      RequiredPurchase(itemId: "item.food", quantity: 1, fulfilled: true),
      RequiredPurchase(itemId: "item.hygiene", quantity: 1, fulfilled: true),
    ],
    purchaseSlotsTotal: 3,
    purchaseSlotsUsed: 2,
    purchasedItemIds: ["item.food", "item.hygiene"],
    budgetPlan: BudgetPlan(
      periodId: "profile.demo.01.g1.p1",
      needsLimit: 50,
      wantsLimit: 20,
      savingsTarget: 30,
      unallocatedAmount: 0,
      requiredNeedsCostAtConfirmation: 50,
      confirmedAt: DateTime.parse("2026-09-24T09:02:00Z"),
    ),
    actual: BudgetActual(
      periodIncome: 100,
      taskRewards: 10,
      needsSpent: 50,
      wantsSpent: 0,
      savingsDeposited: 30,
      ordinarySavingsWithdrawn: 0,
      goalRedemptionSpent: 0,
      qualifyingSavings: 30,
      savingsMoodBonusGranted: true,
      requiredNeedsMet: true,
      planKept: true,
      savingsHabitKept: true,
    ),
    startedAt: DateTime.parse("2026-09-24T09:00:00Z"),
    closedAt: DateTime.parse("2026-09-24T09:20:00Z"),
  ),
  availableBalance: 30,
  savingsBalance: 30,
  activeGoal: GoalProgress(
    goalId: "goal.playground",
    title: "Игровая площадка для Финни",
    targetAmount: 120,
    savedAmount: 30,
    remainingAmount: 90,
    status: GoalStatus.selected,
    selectedAt: DateTime.parse("2026-09-24T09:03:00Z"),
    completedAt: null,
  ),
  pet: PetState(
    name: "Финни",
    formId: "pet.form.01",
    paletteId: "pet.palette.01",
    satiety: 65,
    mood: 84,
    moodCode: MoodCode.happy,
    stage: PetStage.baby,
    lastReasonCode: "period_finished_strong",
    explanationForChild: "Хороший период: нужное и план помогли Финни.",
  ),
  taskHub: TaskHub(
    recommendedTask: TaskSummary(
      id: "task.budget.02",
      title: "Сравни план и факт",
      theme: TaskTheme.budget,
      interactionType: TaskInteractionType.planFactChoice,
      rewardAmount: 5,
      availability: TaskAvailabilityCode.periodClosed,
      unavailableReason: "Сначала начни следующий период.",
      completed: false,
      rewardState: RewardState.available,
      attemptsThisPeriod: 0,
      remainingAttempts: 3,
    ),
    tasks: [
      TaskSummary(
        id: "task.budget.01",
        title: "Распредели доход",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.budgetAllocation,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.completedReview,
        unavailableReason: null,
        completed: true,
        rewardState: RewardState.granted,
        attemptsThisPeriod: 1,
        remainingAttempts: 2,
      ),
      TaskSummary(
        id: "task.budget.02",
        title: "Сравни план и факт",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.planFactChoice,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.periodClosed,
        unavailableReason: "Сначала начни следующий период.",
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.savings.01",
        title: "Составь путь к цели",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsSchedule,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.completedReview,
        unavailableReason: null,
        completed: true,
        rewardState: RewardState.granted,
        attemptsThisPeriod: 1,
        remainingAttempts: 2,
      ),
      TaskSummary(
        id: "task.savings.02",
        title: "Посчитай накопления",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsComparison,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.periodClosed,
        unavailableReason: "Сначала начни следующий период.",
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.01",
        title: "Собери корзину",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.purchaseBasket,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.periodClosed,
        unavailableReason: "Сначала начни следующий период.",
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.02",
        title: "Нужное или желаемое",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.expenseClassification,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.periodClosed,
        unavailableReason: "Сначала начни следующий период.",
        completed: false,
        rewardState: RewardState.available,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
    ],
  ),
  learningProgress: LearningProgress(
    completedPeriods: 1,
    qualityPoints: 3,
    taskProgress: [
      TaskProgress(
        taskId: "task.budget.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 1,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:05:00Z"),
      ),
      TaskProgress(
        taskId: "task.budget.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.savings.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 1,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:07:00Z"),
      ),
      TaskProgress(
        taskId: "task.savings.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.01",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
      TaskProgress(
        taskId: "task.payments.02",
        completed: false,
        attemptsTotal: 0,
        attemptsThisPeriod: 0,
        lastOutcome: null,
        rewardState: RewardState.available,
        completedAt: null,
      ),
    ],
    stageHistory: [
      StageHistoryEntry(
        stage: PetStage.baby,
        reachedAfterPeriod: 0,
        qualityPoints: 0,
        reachedAt: DateTime.parse("2026-09-24T09:00:00Z"),
      ),
    ],
  ),
  settings: ProfileSettings(
    soundEnabled: true,
    reducedMotion: false,
    largeTextPreferred: false,
  ),
);
GameState completedFixture() => GameState(
  contractVersion: "logic_contract_v0.1",
  contentVersion: "content_v0.2",
  stateRevision: 46,
  profile: Profile(
    id: "profile.demo.01",
    mode: ProfileMode.demo,
    displayName: null,
    petName: "Финни",
    generation: 1,
    createdAt: DateTime.parse("2026-09-24T09:00:00Z"),
    updatedAt: DateTime.parse("2026-09-24T10:30:00Z"),
  ),
  currentPeriod: PeriodState(
    id: "profile.demo.01.g1.p5",
    number: 5,
    status: PeriodStatus.demoCompleted,
    incomeCredited: 100,
    incomeCreditedAt: DateTime.parse("2026-09-24T10:00:00Z"),
    availableItemIds: ["item.food", "item.hygiene", "item.ball", "item.hat"],
    requiredPurchases: [
      RequiredPurchase(itemId: "item.food", quantity: 1, fulfilled: true),
      RequiredPurchase(itemId: "item.hygiene", quantity: 1, fulfilled: true),
    ],
    purchaseSlotsTotal: 3,
    purchaseSlotsUsed: 3,
    purchasedItemIds: ["item.food", "item.hygiene", "item.ball"],
    budgetPlan: BudgetPlan(
      periodId: "profile.demo.01.g1.p5",
      needsLimit: 50,
      wantsLimit: 35,
      savingsTarget: 30,
      unallocatedAmount: 0,
      requiredNeedsCostAtConfirmation: 50,
      confirmedAt: DateTime.parse("2026-09-24T10:02:00Z"),
    ),
    actual: BudgetActual(
      periodIncome: 100,
      taskRewards: 5,
      needsSpent: 50,
      wantsSpent: 35,
      savingsDeposited: 30,
      ordinarySavingsWithdrawn: 0,
      goalRedemptionSpent: 120,
      qualifyingSavings: 30,
      savingsMoodBonusGranted: true,
      requiredNeedsMet: true,
      planKept: true,
      savingsHabitKept: true,
    ),
    startedAt: DateTime.parse("2026-09-24T10:00:00Z"),
    closedAt: DateTime.parse("2026-09-24T10:30:00Z"),
  ),
  availableBalance: 5,
  savingsBalance: 25,
  activeGoal: null,
  pet: PetState(
    name: "Финни",
    formId: "pet.form.01",
    paletteId: "pet.palette.01",
    satiety: 85,
    mood: 100,
    moodCode: MoodCode.happy,
    stage: PetStage.grown,
    lastReasonCode: "period_finished_strong",
    explanationForChild: "Пять периодов завершены. Можно посмотреть результаты или начать демо заново.",
  ),
  taskHub: TaskHub(
    recommendedTask: null,
    tasks: [
      TaskSummary(
        id: "task.budget.01",
        title: "Распредели доход",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.budgetAllocation,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.demoCompletedReview,
        unavailableReason: "Награда уже получена; доступен просмотр.",
        completed: true,
        rewardState: RewardState.alreadyGranted,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.budget.02",
        title: "Сравни план и факт",
        theme: TaskTheme.budget,
        interactionType: TaskInteractionType.planFactChoice,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.demoCompletedReview,
        unavailableReason: "Награда уже получена; доступен просмотр.",
        completed: true,
        rewardState: RewardState.alreadyGranted,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.savings.01",
        title: "Составь путь к цели",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsSchedule,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.demoCompletedReview,
        unavailableReason: "Награда уже получена; доступен просмотр.",
        completed: true,
        rewardState: RewardState.alreadyGranted,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.savings.02",
        title: "Посчитай накопления",
        theme: TaskTheme.savings,
        interactionType: TaskInteractionType.savingsComparison,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.demoCompletedReview,
        unavailableReason: "Награда уже получена; доступен просмотр.",
        completed: true,
        rewardState: RewardState.alreadyGranted,
        attemptsThisPeriod: 1,
        remainingAttempts: 2,
      ),
      TaskSummary(
        id: "task.payments.01",
        title: "Собери корзину",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.purchaseBasket,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.demoCompletedReview,
        unavailableReason: "Награда уже получена; доступен просмотр.",
        completed: true,
        rewardState: RewardState.alreadyGranted,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
      TaskSummary(
        id: "task.payments.02",
        title: "Нужное или желаемое",
        theme: TaskTheme.paymentsAndPurchases,
        interactionType: TaskInteractionType.expenseClassification,
        rewardAmount: 5,
        availability: TaskAvailabilityCode.demoCompletedReview,
        unavailableReason: "Награда уже получена; доступен просмотр.",
        completed: true,
        rewardState: RewardState.alreadyGranted,
        attemptsThisPeriod: 0,
        remainingAttempts: 3,
      ),
    ],
  ),
  learningProgress: LearningProgress(
    completedPeriods: 5,
    qualityPoints: 15,
    taskProgress: [
      TaskProgress(
        taskId: "task.budget.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 0,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:05:00Z"),
      ),
      TaskProgress(
        taskId: "task.budget.02",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 0,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:50:00Z"),
      ),
      TaskProgress(
        taskId: "task.savings.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 0,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:07:00Z"),
      ),
      TaskProgress(
        taskId: "task.savings.02",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 1,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T10:05:00Z"),
      ),
      TaskProgress(
        taskId: "task.payments.01",
        completed: true,
        attemptsTotal: 1,
        attemptsThisPeriod: 0,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:25:00Z"),
      ),
      TaskProgress(
        taskId: "task.payments.02",
        completed: true,
        attemptsTotal: 2,
        attemptsThisPeriod: 0,
        lastOutcome: TaskAttemptOutcome.correct,
        rewardState: RewardState.granted,
        completedAt: DateTime.parse("2026-09-24T09:38:00Z"),
      ),
    ],
    stageHistory: [
      StageHistoryEntry(
        stage: PetStage.baby,
        reachedAfterPeriod: 0,
        qualityPoints: 0,
        reachedAt: DateTime.parse("2026-09-24T09:00:00Z"),
      ),
      StageHistoryEntry(
        stage: PetStage.junior,
        reachedAfterPeriod: 2,
        qualityPoints: 6,
        reachedAt: DateTime.parse("2026-09-24T09:30:00Z"),
      ),
      StageHistoryEntry(
        stage: PetStage.grown,
        reachedAfterPeriod: 4,
        qualityPoints: 12,
        reachedAt: DateTime.parse("2026-09-24T10:00:00Z"),
      ),
    ],
  ),
  settings: ProfileSettings(
    soundEnabled: true,
    reducedMotion: false,
    largeTextPreferred: false,
  ),
);
